repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: This hook runs flake8 in the active python environment.
        entry: flake8
        language: python
        types: [python]
        require_serial: true
