name: Check Submodules

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  check-submodules:
    name: Check if submodules need updates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for available submodule updates
      id: check
      run: |
        # Update submodules to see what's available (without committing)
        git submodule update --recursive --remote
        
        # Check if there are any changes
        if git diff --quiet; then
          echo "needs_update=false" >> $GITHUB_OUTPUT
          echo "No submodule updates available"
        else
          echo "needs_update=true" >> $GITHUB_OUTPUT
          echo "Submodule updates are available:"
          git diff --name-only
          
          # Get the exact commands needed
          echo "commands<<EOF" >> $GITHUB_OUTPUT
          echo "git submodule update --recursive --remote" >> $GITHUB_OUTPUT
          echo "git add ." >> $GITHUB_OUTPUT
          echo 'git commit -m "chore: update submodules to latest versions"' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
        
    - name: Comment on PR if updates needed
      if: steps.check.outputs.needs_update == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const commands = `${{ steps.check.outputs.commands }}`;
          const body = `## 🔄 Submodule Updates Available
          
          This PR can be updated to use the latest versions of git submodules.
          
          **To update submodules, run these commands:**
          \`\`\`bash
          ${commands}
          \`\`\`
          
          This will ensure your PR uses the most recent versions of Bulma and extensions.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });