name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_HOME: ${{ github.workspace }}/pre-commit-cache
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Restore pre-commit environment
        uses: actions/cache@v4
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: "${{ runner.os }}-\
            precommit-\
            ${{ steps.python.outputs.python-version }}-\
            ${{ hashFiles('.pre-commit-config.yaml') }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
