name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  check-submodules:
    name: Check submodules
    uses: ./.github/workflows/check-submodules.yml

  bump-pyproject-version:
    name: Bump version in setup.py
    runs-on: ubuntu-latest
    needs: check-submodules
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Extract version from tag
      id: get_version
      run: |
        # Remove 'v' prefix if present
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Update version in setup.py
      run: |
        sed -i "s/version=\".*\"/version=\"${{ steps.get_version.outputs.VERSION }}\"/" setup.py
        
    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add setup.py
        git commit -m "🔖 Bump version to ${{ steps.get_version.outputs.VERSION }}"
        git push

  publish-to-pypi:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    needs: bump-pyproject-version
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: python -m build
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}