name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  check-submodules:
    name: Check submodules
    uses: ./.github/workflows/check-submodules.yml

  build:
    name: Build dist & publish
    runs-on: ubuntu-latest
    needs: check-submodules

    steps:
    - name: Checkout the repo and the submodules.
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Clean previous builds
      run: rm -rf dist build *.egg-info

    - name: Install build dependencies & build
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.12.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
