name: Test with pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
        django-version: ['4.2', '5.2']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras
          uv pip install "Django~=${{ matrix.django-version }}.0"

      - name: Run tests
        run: |
          uv run pytest -v --tb=short

      - name: Run tests with coverage
        if: matrix.python-version == '3.12' && matrix.django-version == '4.2'
        run: |
          uv run coverage run -m pytest
          uv run coverage report --show-missing
          uv run coverage xml

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request' && matrix.python-version == '3.12' && matrix.django-version == '4.2'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MINIMUM_GREEN: 85
          MINIMUM_ORANGE: 70
